### ISSUE TITLE
WHY?????

### ISSUE THREAD

**Issue by charlesmanson13** [zack-bitcoin/light-node-amoveo#1]
<img width="499" alt="screenshot 2018-11-14 at 17 29 41" src="https://user-images.githubusercontent.com/8911442/48489333-da679e00-e833-11e8-9e7f-04a0f3ac0aaf.png">

**Comment by zack-bitcoin** [comment]
What is this a picture of?
why what?

**Comment by charlesmanson13** [comment]
This is your code. Mixed tabs and spaces indentation. And it's completely unreadable.

**Comment by zack-bitcoin** [comment]
https://github.com/zack-bitcoin/light-node-amoveo/blob/master/src/js/keys.js#L50
aha, I found it.

It looks fine in emacs, and it looks fine on github.

It sure looks ugly in your editor. I can't read it either.
Maybe you should switch to a better editor.

**Comment by zack-bitcoin** [comment]
you could also write a script to reformat to the way you like to read it.

If a script to change spaces to tabs is too complicated for you, then we probably don't need your help with Amoveo anyway.
